// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/record": {
            "put": {
                "description": "update a record within the json file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "update record",
                "parameters": [
                    {
                        "description": "record to be updated",
                        "name": "record",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/jsonFile.Record"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "updated record",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "header"
                        }
                    }
                }
            },
            "post": {
                "description": "create a record within the json file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "create record",
                "parameters": [
                    {
                        "description": "record to be created",
                        "name": "record",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/jsonFile.Record"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "created record",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "400": {
                        "description": "failure message saying resource already exists",
                        "schema": {
                            "type": "header"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "header"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete a record within the json file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "delete record",
                "parameters": [
                    {
                        "description": "record to be deleted",
                        "name": "record",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/jsonFile.Record"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "deleted record",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "header"
                        }
                    }
                }
            }
        },
        "/records": {
            "get": {
                "description": "gets all records within the json file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "get all records",
                "responses": {
                    "200": {
                        "description": "get all records",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "header"
                        }
                    }
                }
            }
        },
        "/records/{name}": {
            "get": {
                "description": "gets a record within the json file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "get a single record",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "get a records",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "header"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "jsonFile.Record": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer"
                },
                "designation": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "todos": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Simple Json App",
	Description:      "This is a simple json app, apis of which will be fed into a crossplane provider.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
