# NOTE: This file is a template, and might need editing before it works on your project.

###  For more information on configuration, see reference(s):
###    - https://docs.gitlab.com/ee/ci/yaml/
image: docker.nexus.heb.tools/busybox:latest

variables:
  # Please edit to your GitLab project
  CI_REGISTRY: "harbor.heb.com"
  CI_REGISTRY_PROJECT: "kon.kon-admin"
  CI_REGISTRY_IMAGE: "deploy-restarter"

stages:
  - test
  - build

unit_tests:
  stage: test
  tags:
    - KON_OWNER:KON-ADMIN
    - KON_ENVTYPE:NONPROD
  image:
    name: golang:latest
  script:
    - go test ./... -race

build_only:
  stage: build
  retry: 2
  tags:
    - KON_OWNER:KON-ADMIN
    - KON_ENVTYPE:NONPROD
  image:
    # must be pinned to v0.16.0. Otherwise, authentication will not work.
    name: gcr.io/kaniko-project/executor:debug-v0.16.0
    entrypoint: [""]
  script:
    - CMD="/kaniko/executor --no-push --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY/$CI_REGISTRY_PROJECT/$CI_REGISTRY_IMAGE:${CI_COMMIT_TAG:-${CI_COMMIT_SHORT_SHA}}"
    - echo "$CMD" && eval "$CMD"

build_and_push:
  stage: build
  retry: 2
  tags:
    - KON_OWNER:KON-ADMIN
    - KON_ENVTYPE:NONPROD
  image:
    # must be pinned to v0.16.0. Otherwise, authentication will not work.
    name: gcr.io/kaniko-project/executor:debug-v0.16.0
    entrypoint: [""]
  before_script:
    # Authenticate to Harbor registry using credentials embedded on the team's Gitlab runners
    - . /home/gitlab-runner/docker-login
  script:
    # Push docker image with tag equal to CI_COMMIT_TAG if present or CI_COMMIT_SHORT_SHA if not
    - CMD="/kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY/$CI_REGISTRY_PROJECT/$CI_REGISTRY_IMAGE:${CI_COMMIT_TAG:-${CI_COMMIT_SHORT_SHA}}"
    - echo "$CMD" && eval "$CMD"
  allow_failure: false
  # Limit this step to the Branch set as default on the repository
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
